### ISSUE TITLE
How to get Element

### ISSUE THREAD

**Issue by magic-77** [marksturm/newsapp4contao#1]
Nice Plugin, but how to get an Element like Page Id is 15, and has an Text Element with Id (tl_content) 56
Get always an "ERROR"

**Comment by marksturm** [comment]
Sry, long time ago:
http://api.yourdomain.tdl/?modul=Element&ptable=tl_articlet&id=56

Maybe this will help you to get in touch with the api:
https://github.com/marksturm/app4contao/blob/master/ionic/www/js/services/services.js#L48

**Comment by magic-77** [comment]
Hi Mark, thanks for the quick reply. But it does not work for me. Using Contao 3.5.34.
Tried some Combinations with IDs, without success.

This is my Structure, and calling ?modul=Element give me the first Content Element


On Layout -> Pages the target Page Id = 15, inside it has an Text Element with Id = 56, this is my Target

**Comment by marksturm** [comment]
edited: http://api.yourdomain.tdl/?modul=Element&ptable=tl_articlet&id=56

**Comment by magic-77** [comment]
Thanks to Mark helping me with this
